defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password: 1Welcome
  pool: 5
  host: localhost


test: &test
  <<: *defaults
  database: timestack_test

development:
  <<: *defaults
  database: timestack


cucumber:
  <<: *test
